// NA6PCCopyright

// Based on:
// Copyright 2019-2020 CERN and copyright holders of ALICE O2.
// See https://alice-o2.web.cern.ch/copyright for details of the copyright holders.
// All rights not expressly granted are reserved.
//
// This software is distributed under the terms of the GNU General Public
// License v3 (GPL Version 3), copied verbatim in the file "COPYING".
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

/// \file PhysicsConstants.h
/// \brief Header to collect physics constants
/// \author ruben.shahoyan@cern.ch
/// \author Vít Kučera <vit.kucera@cern.ch>, Inha University
/// \note Use the make_pdg_header.py script to generate the enums and mass declarations.

#ifndef NA6P_PHYSICSCONSTANTS_H_
#define NA6P_PHYSICSCONSTANTS_H_

namespace phys_const
{
// particles masses

// BEGINNING OF THE GENERATED BLOCK.
// DO NOT EDIT THIS BLOCK DIRECTLY!
// It has been generated by the make_pdg_header.py script.
// For modifications, edit the script and generate this block again.

/// \brief Declarations of named PDG codes of particles missing in ROOT PDG_t
/// \note Follow kCamelCase naming convention
/// \link https://root.cern/doc/master/TPDGCode_8h.html
enum Pdg {
  kEta = 221,
  kOmega = 223,
  kEtaPrime = 331,
  kB0 = 511,
  kB0Bar = -511,
  kBPlus = 521,
  kBCPlus = 541,
  kBS = 531,
  kBSBar = -531,
  kD0 = 421,
  kD0Bar = -421,
  kD0StarPlus = 10411,
  kD0Star0 = 10421,
  kD1Plus = 20413,
  kD10 = 20423,
  kD2StarPlus = 415,
  kD2Star0 = 425,
  kDMinus = -411,
  kDPlus = 411,
  kDS = 431,
  kDSBar = -431,
  kDSStar = 433,
  kDS1 = 10433,
  kDS1Star2700 = 30433,
  kDS1Star2860 = 40433,
  kDS2Star = 435,
  kDS3Star2860 = 437,
  kDStar = 413,
  kDStar0 = 423,
  kChiC1 = 20443,
  kJPsi = 443,
  kLambdaB0 = 5122,
  kLambdaCPlus = 4122,
  kOmegaC0 = 4332,
  kK0Star892 = 313,
  kKPlusStar892 = 323,
  kPhi = 333,
  kSigmaC0 = 4112,
  kSigmaCPlusPlus = 4222,
  kSigmaCStar0 = 4114,
  kSigmaCStarPlusPlus = 4224,
  kX3872 = 9920443,
  kXi0 = 3322,
  kXiB0 = 5232,
  kXiCCPlusPlus = 4422,
  kXiCPlus = 4232,
  kXiC0 = 4132,
  kXiC3055Plus = 4325,
  kXiC3080Plus = 4326,
  kXiC3055_0 = 4315,
  kXiC3080_0 = 4316,
  kDeuteron = 1000010020,
  kTriton = 1000010030,
  kHelium3 = 1000020030,
  kAlpha = 1000020040,
  kLithium4 = 1000030040,
  kHyperTriton = 1010010030,
  kHyperHydrogen4 = 1010010040,
  kHyperHelium4 = 1010020040,
  kHyperHelium5 = 1010020050,
  kHyperHelium4Sigma = 1110020040,
  kLambda1520_Py = 102134
};

/// \brief Declarations of masses for additional particles
constexpr float MassEta = 0.547862;
constexpr float MassOmega = 0.78266;
constexpr float MassEtaPrime = 0.95778;
constexpr float MassB0 = 5.27966;
constexpr float MassB0Bar = 5.27966;
constexpr float MassBPlus = 5.27934;
constexpr float MassBCPlus = 6.27447;
constexpr float MassBS = 5.36692;
constexpr float MassBSBar = 5.36692;
constexpr float MassD0 = 1.86484;
constexpr float MassD0Bar = 1.86484;
constexpr float MassD0StarPlus = 2.272;
constexpr float MassD0Star0 = 2.343;
constexpr float MassD1Plus = 2.372;
constexpr float MassD10 = 2.412;
constexpr float MassD2StarPlus = 2.4601;
constexpr float MassD2Star0 = 2.4611;
constexpr float MassDMinus = 1.86966;
constexpr float MassDPlus = 1.86966;
constexpr float MassDS = 1.96835;
constexpr float MassDSBar = 1.96835;
constexpr float MassDSStar = 2.1122;
constexpr float MassDS1 = 2.53511;
constexpr float MassDS1Star2700 = 2.714;
constexpr float MassDS1Star2860 = 2.859;
constexpr float MassDS2Star = 2.5691;
constexpr float MassDS3Star2860 = 2.86;
constexpr float MassDStar = 2.01026;
constexpr float MassDStar0 = 2.00685;
constexpr float MassChiC1 = 3.51067;
constexpr float MassJPsi = 3.0969;
constexpr float MassLambdaB0 = 5.6196;
constexpr float MassLambdaCPlus = 2.28646;
constexpr float MassOmegaC0 = 2.6952;
constexpr float MassK0Star892 = 0.89555;
constexpr float MassKPlusStar892 = 0.89167;
constexpr float MassPhi = 1.019461;
constexpr float MassSigmaC0 = 2.45375;
constexpr float MassSigmaCPlusPlus = 2.45397;
constexpr float MassSigmaCStar0 = 2.51848;
constexpr float MassSigmaCStarPlusPlus = 2.51841;
constexpr float MassX3872 = 3.87165;
constexpr float MassXi0 = 1.31486;
constexpr float MassXiB0 = 5.7919;
constexpr float MassXiCCPlusPlus = 3.62155;
constexpr float MassXiCPlus = 2.46771;
constexpr float MassXiC0 = 2.47044;
constexpr float MassXiC3055Plus = 3.0559;
constexpr float MassXiC3080Plus = 3.0772;
constexpr float MassXiC3055_0 = 3.059;
constexpr float MassXiC3080_0 = 3.0799;
constexpr float MassDeuteron = 1.87561294257;
constexpr float MassTriton = 2.80892113298;
constexpr float MassHelium3 = 2.80839160743;
constexpr float MassAlpha = 3.7273794066;
constexpr float MassLithium4 = 3.7513;
constexpr float MassHyperTriton = 2.991134;
constexpr float MassHyperHydrogen4 = 3.922434;
constexpr float MassHyperHelium4 = 3.921728;
constexpr float MassHyperHelium5 = 4.839961;
constexpr float MassHyperHelium4Sigma = 3.995;
constexpr float MassLambda1520_Py = 1.5195;

/// \brief Declarations of masses for particles in ROOT PDG_t
constexpr float MassDown = 0.00467;
constexpr float MassDownBar = 0.00467;
constexpr float MassUp = 0.00216;
constexpr float MassUpBar = 0.00216;
constexpr float MassStrange = 0.0934;
constexpr float MassStrangeBar = 0.0934;
constexpr float MassCharm = 1.27;
constexpr float MassCharmBar = 1.27;
constexpr float MassBottom = 4.18;
constexpr float MassBottomBar = 4.18;
constexpr float MassTop = 172.5;
constexpr float MassTopBar = 172.5;
constexpr float MassGluon = 0.0;
constexpr float MassElectron = 0.000510999;
constexpr float MassPositron = 0.000510999;
constexpr float MassNuE = 0.0;
constexpr float MassNuEBar = 0.0;
constexpr float MassMuonMinus = 0.1056584;
constexpr float MassMuonPlus = 0.1056584;
constexpr float MassNuMu = 0.0;
constexpr float MassNuMuBar = 0.0;
constexpr float MassTauMinus = 1.77686;
constexpr float MassTauPlus = 1.77686;
constexpr float MassNuTau = 0.0;
constexpr float MassNuTauBar = 0.0;
constexpr float MassGamma = 0.0;
constexpr float MassZ0 = 91.1876;
constexpr float MassWPlus = 80.377;
constexpr float MassWMinus = 80.377;
constexpr float MassPi0 = 0.1349768;
constexpr float MassK0Long = 0.497611;
constexpr float MassPiPlus = 0.1395704;
constexpr float MassPiMinus = 0.1395704;
constexpr float MassProton = 0.9382721;
constexpr float MassProtonBar = 0.9382721;
constexpr float MassNeutron = 0.9395654;
constexpr float MassNeutronBar = 0.9395654;
constexpr float MassK0Short = 0.497611;
constexpr float MassK0 = 0.497611;
constexpr float MassK0Bar = 0.497611;
constexpr float MassKPlus = 0.493677;
constexpr float MassKMinus = 0.493677;
constexpr float MassLambda0 = 1.115683;
constexpr float MassLambda0Bar = 1.115683;
constexpr float MassLambda1520 = 1.519;
constexpr float MassSigmaMinus = 1.197449;
constexpr float MassSigmaBarPlus = 1.197449;
constexpr float MassSigmaPlus = 1.18937;
constexpr float MassSigmaBarMinus = 1.18937;
constexpr float MassSigma0 = 1.192642;
constexpr float MassSigma0Bar = 1.192642;
constexpr float MassXiMinus = 1.32171;
constexpr float MassXiPlusBar = 1.32171;
constexpr float MassOmegaMinus = 1.67245;
constexpr float MassOmegaPlusBar = 1.67245;

// END OF THE GENERATED BLOCK

// legacy names
constexpr float MassPhoton = MassGamma;
constexpr float MassMuon = MassMuonMinus;
constexpr float MassPionCharged = MassPiPlus;
constexpr float MassPionNeutral = MassPi0;
constexpr float MassKaonCharged = MassKPlus;
constexpr float MassKaonNeutral = MassK0;
constexpr float MassLambda = MassLambda0;
constexpr float MassHyperhydrog4 = MassHyperHydrogen4;
constexpr float MassHyperhelium4 = MassHyperHelium4;
constexpr float MassHyperhelium4sigma = MassHyperHelium4Sigma;

// Light speed
constexpr float LightSpeedCm2S = 299792458.e2;            // C in cm/s
constexpr float LightSpeedCm2NS = LightSpeedCm2S * 1e-9;  // C in cm/ns
constexpr float LightSpeedCm2PS = LightSpeedCm2S * 1e-12; // C in cm/ps

// Light speed inverse
constexpr float invLightSpeedCm2PS = 1. / LightSpeedCm2PS; // 1/C in ps/cm

} // namespace phys_const

#endif
